# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

# Generates hrr_build_info.h, the source revision that hrr-playback --version
# reports.
#
# Run from a build rule (cmake -P) rather than at configure time: a stamp taken
# at configure time keeps reporting whatever was checked out then, which is the
# one answer worse than no answer for a tool whose purpose is to tell you which
# build you are holding. The header is rewritten only when its contents change,
# so an unchanged revision does not relink hrr-playback on every build.

if(NOT DEFINED SRC_DIR OR NOT DEFINED OUT_FILE)
  message(FATAL_ERROR "HrrVersionStamp.cmake requires -DSRC_DIR= and -DOUT_FILE=")
endif()

set(HRR_BUILD_REV "unknown")
set(HRR_BUILD_BRANCH "unknown")

# HRR is routinely built in a container against a source tree bind-mounted from
# the host, where the tree's owner is not the build user and git refuses to read
# it at all ("detected dubious ownership") - which would leave every such build
# reporting an unknown revision. safe.directory is honoured only from a config
# *file*: neither "git -c safe.directory=*" nor GIT_CONFIG_COUNT injection is
# accepted. So point git at a throwaway global config for these read-only
# queries instead of modifying the user's real one.
get_filename_component(_out_dir "${OUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")
set(_git_config "${_out_dir}/hrr_version_stamp.gitconfig")
if(NOT EXISTS "${_git_config}")
  file(WRITE "${_git_config}" "[safe]\n\tdirectory = *\n")
endif()
set(ENV{GIT_CONFIG_GLOBAL} "${_git_config}")

find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE _rev
    RESULT_VARIABLE _rev_res
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  if(_rev_res EQUAL 0 AND NOT _rev STREQUAL "")
    set(HRR_BUILD_REV "${_rev}")

    # HRR is normally built from a tree carrying local changes, so a revision
    # that ignored them would point at code that was never compiled.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
      WORKING_DIRECTORY "${SRC_DIR}"
      OUTPUT_VARIABLE _dirty
      RESULT_VARIABLE _dirty_res
      ERROR_QUIET
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(_dirty_res EQUAL 0 AND NOT _dirty STREQUAL "")
      set(HRR_BUILD_REV "${HRR_BUILD_REV}-dirty")
    endif()

    execute_process(
      COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
      WORKING_DIRECTORY "${SRC_DIR}"
      OUTPUT_VARIABLE _branch
      RESULT_VARIABLE _branch_res
      ERROR_QUIET
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(_branch_res EQUAL 0 AND NOT _branch STREQUAL "")
      set(HRR_BUILD_BRANCH "${_branch}")
    endif()
  endif()
endif()

set(_content
"// Generated by HrrVersionStamp.cmake at build time - do not edit.
#pragma once
#define HRR_BUILD_REV \"${HRR_BUILD_REV}\"
#define HRR_BUILD_BRANCH \"${HRR_BUILD_BRANCH}\"
")

set(_existing "")
if(EXISTS "${OUT_FILE}")
  file(READ "${OUT_FILE}" _existing)
endif()
if(NOT _existing STREQUAL _content)
  file(WRITE "${OUT_FILE}" "${_content}")
endif()
