/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Multi-rank / multi-node tests for ncclConfig_t::maxP2pPeers and its environment
// override NCCL_P2P_MAX_PEERS (NCCL 2.30.4 sync). The knob is the divisor both
// per-peer channel heuristics in ncclTopoComputeP2pChannels use; unset resolves to
// the communicator size, which is why the default path is unaffected.
//
// Execution model: env cases need one mpirun per test (see MPITestCore.cpp) because
// NCCL_PARAM caches per process. They GTEST_SKIP if the value is already cached.
//
// Config injection lives here rather than TestBed because TestBedChild::InitComms
// only builds an ncclConfig_t on the non-blocking path. For a broad correctness
// sweep use the env: NCCL_P2P_MAX_PEERS=2 ./rccl-UnitTests --gtest_filter='*AllToAll*'

#ifdef MPI_TESTS_ENABLED

#include "MPITestBase.hpp"
#include "ResourceGuards.hpp"
#include "TestChecks.hpp"

#include "comm.h" // internal: struct ncclComm::config, p2pMaxPeers, p2pnChannelsPerPeer

#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <hip/hip_runtime.h>
#include <mpi.h>

using namespace MPITestConstants;
using namespace RCCLTestGuards;

// Generated by NCCL_PARAM(MaxP2pPeers, ...) in src/init.cc. Used to detect a stale
// per-process cache so the env tests can SKIP rather than report a false failure.
int64_t ncclParamMaxP2pPeers();
// Likewise from RCCL_PARAM(SaturateP2pNChannels, ...) in src/graph/paths.cc.
int64_t rcclParamSaturateP2pNChannels();

namespace
{
// Sentinel meaning "leave the config field at its default (UNDEF)".
constexpr int kLeaveConfigUnset = NCCL_CONFIG_UNDEF_INT;
} // namespace

/**
 * @class MaxP2pPeersMPITest
 * @brief Multi-rank fixture that injects maxP2pPeers via config and/or the
 *        NCCL_P2P_MAX_PEERS env, then exposes the live communicator.
 *
 * Mirrors NChannelsPerNetPeerMPITests.cpp: overrides createTestCommunicator() while
 * reusing the base members, so getActiveCommunicator()/getActiveStream() keep working.
 */
class MaxP2pPeersMPITest : public MPITestBase
{
protected:
    // Config field to request. kLeaveConfigUnset leaves it UNDEF.
    int configured_value_ = kLeaveConfigUnset;

    // Returns the raw result so the rejection case can assert on ncclInvalidArgument.
    ncclResult_t tryCreateCommunicator()
    {
        int world_rank = MPIEnvironment::world_rank;
        int world_size = MPIEnvironment::world_size;

        if(world_rank == 0)
        {
            RCCL_TEST_CHECK(ncclGetUniqueId(&nccl_id_));
        }
        MPI_Bcast(&nccl_id_, sizeof(ncclUniqueId), MPI_BYTE, 0, MPI_COMM_WORLD);

        ncclConfig_t config = NCCL_CONFIG_INITIALIZER;
        config.maxP2pPeers  = configured_value_;

        // No group wrapper: an invalid config must surface its own error code.
        ncclResult_t res =
            ncclCommInitRankConfig(&test_comm_, world_size, nccl_id_, world_rank, &config);
        if(res != ncclSuccess)
        {
            test_comm_ = nullptr;
            MPI_Barrier(MPI_COMM_WORLD);
            return res;
        }

        auto comm_guard = makeScopeGuard(
            [this]()
            {
                if(test_comm_)
                {
                    (void)ncclCommDestroy(test_comm_);
                    test_comm_ = nullptr;
                }
            });

        HIP_TEST_CHECK(hipStreamCreate(&test_stream_));
        auto stream_guard = makeScopeGuard(
            [this]()
            {
                if(test_stream_)
                {
                    (void)hipStreamDestroy(test_stream_);
                    test_stream_ = nullptr;
                }
            });

        MPI_Barrier(MPI_COMM_WORLD);

        comm_guard.dismiss();
        stream_guard.dismiss();

        if(world_rank == 0)
        {
            TEST_INFO("Communicator created; config.maxP2pPeers=%d p2pMaxPeers=%d "
                      "p2pnChannels=%d p2pnChannelsPerPeer=%d",
                      test_comm_->config.maxP2pPeers, test_comm_->p2pMaxPeers,
                      test_comm_->p2pnChannels, test_comm_->p2pnChannelsPerPeer);
        }
        return ncclSuccess;
    }

    ncclResult_t createTestCommunicator() override { return tryCreateCommunicator(); }

    // All ranks resolved the same value, whatever it is. Every rank participates.
    void expectAllRanksAgree(int local_value)
    {
        int min_value = 0;
        int max_value = 0;
        ASSERT_MPI_SUCCESS(
            MPI_Allreduce(&local_value, &min_value, 1, MPI_INT, MPI_MIN, MPI_COMM_WORLD));
        ASSERT_MPI_SUCCESS(
            MPI_Allreduce(&local_value, &max_value, 1, MPI_INT, MPI_MAX, MPI_COMM_WORLD));
        ASSERT_MPI_EQ(min_value, max_value);
    }

    // The pair every resolution test checks: what the user asked for, what paths.cc will
    // divide by, and that the ranks agree on it. The two differ only when the field is
    // left UNDEF, where the divisor resolves to the communicator size.
    void expectResolvedMaxP2pPeers(int expectedConfig, int expectedResolved)
    {
        ASSERT_MPI_EQ(getActiveCommunicator()->config.maxP2pPeers, expectedConfig);
        ASSERT_MPI_EQ(getActiveCommunicator()->p2pMaxPeers, expectedResolved);
        expectAllRanksAgree(getActiveCommunicator()->p2pMaxPeers);
    }

    void expectResolvedMaxP2pPeers(int expected) { expectResolvedMaxP2pPeers(expected, expected); }

    // NCCL_PARAM caches per process, so an earlier test that set the variable pins it for
    // the rest of the binary and unsetenv cannot undo that. Tests needing a particular
    // cached state skip rather than report a failure that is really test ordering.
    bool maxP2pPeersEnvCachedAs(int expected) { return ncclParamMaxP2pPeers() == expected; }

    // Rank r sends its index to every peer, so it must receive [0..world_size-1].
    // The per-peer count feeds ncclP2pChannelForPart/ToPart, whose inverse breaks if
    // it exceeds the pool: wrong data or a hang here means the mapping aliased.
    void expectFunctionalAllToAll()
    {
        const int   world_size = MPIEnvironment::world_size;
        const int   world_rank = MPIEnvironment::world_rank;
        ncclComm_t  comm       = getActiveCommunicator();
        hipStream_t stream     = getActiveStream();
        ASSERT_MPI_TRUE(comm != nullptr && stream != nullptr);

        float* send_dev = nullptr;
        float* recv_dev = nullptr;
        ASSERT_MPI_EQ(hipMalloc(&send_dev, world_size * sizeof(float)), hipSuccess);
        auto send_guard = makeScopeGuard([&]() { (void)hipFree(send_dev); });
        ASSERT_MPI_EQ(hipMalloc(&recv_dev, world_size * sizeof(float)), hipSuccess);
        auto recv_guard = makeScopeGuard([&]() { (void)hipFree(recv_dev); });

        std::vector<float> host(world_size, static_cast<float>(world_rank));
        ASSERT_MPI_EQ(
            hipMemcpy(send_dev, host.data(), world_size * sizeof(float), hipMemcpyHostToDevice),
            hipSuccess);

        // Every check in this function must be collective: a rank returning early would
        // strand the others in ncclGroupEnd or in the allreduces below.
        ncclResult_t op_res = ncclGroupStart();
        for(int peer = 0; peer < world_size; ++peer)
        {
            ncclResult_t s_res = ncclSend(send_dev + peer, 1, ncclFloat, peer, comm, stream);
            ncclResult_t r_res = ncclRecv(recv_dev + peer, 1, ncclFloat, peer, comm, stream);
            if(op_res == ncclSuccess) op_res = s_res;
            if(op_res == ncclSuccess) op_res = r_res;
        }
        ncclResult_t end_res = ncclGroupEnd();
        if(op_res == ncclSuccess) op_res = end_res;
        ASSERT_MPI_EQ(op_res, ncclSuccess);
        ASSERT_MPI_EQ(hipStreamSynchronize(stream), hipSuccess);

        std::vector<float> result(world_size, -1.0f);
        ASSERT_MPI_EQ(
            hipMemcpy(result.data(), recv_dev, world_size * sizeof(float), hipMemcpyDeviceToHost),
            hipSuccess);

        bool local_ok = true;
        for(int i = 0; i < world_size; ++i)
        {
            if(result[i] != static_cast<float>(i))
            {
                local_ok = false;
                TEST_WARN("AllToAll mismatch at [%d]: got %f expected %d", i, result[i], i);
                break;
            }
        }
        ASSERT_MPI_TRUE(local_ok);
    }
};

// ---------------------------------------------------------------------------
// Config field honored across a real multi-rank communicator.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, ConfigField_HonoredAcrossRanks)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    constexpr int kRequested = 4;
    if(MPIEnvironment::world_size < kRequested)
        GTEST_SKIP() << "Needs at least " << kRequested << " ranks to be distinguishable";
    configured_value_ = kRequested;

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());

    expectResolvedMaxP2pPeers(kRequested);
}

// ---------------------------------------------------------------------------
// Env honored across ranks. Asserts behavior, not a log string, so this is the
// authoritative check that the variable is spelled NCCL_P2P_MAX_PEERS.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, Env_HonoredAcrossRanks)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    constexpr int kEnvValue = 4;
    if(MPIEnvironment::world_size < kEnvValue)
        GTEST_SKIP() << "Needs at least " << kEnvValue << " ranks to be distinguishable";
    setenv("NCCL_P2P_MAX_PEERS", std::to_string(kEnvValue).c_str(), /*overwrite=*/1);
    configured_value_ = kLeaveConfigUnset; // env alone drives the value

    if(ncclParamMaxP2pPeers() != kEnvValue)
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());

    expectResolvedMaxP2pPeers(kEnvValue);
}

// ---------------------------------------------------------------------------
// Documented precedence: a valid env value overrides an explicit config field.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, Env_OverridesConfig_AcrossRanks)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    constexpr int kEnvValue = 4;
    if(MPIEnvironment::world_size < kEnvValue)
        GTEST_SKIP() << "Needs at least " << kEnvValue << " ranks to be distinguishable";
    setenv("NCCL_P2P_MAX_PEERS", std::to_string(kEnvValue).c_str(), /*overwrite=*/1);
    configured_value_ = 2; // must lose to the env

    if(ncclParamMaxP2pPeers() != kEnvValue)
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());

    expectResolvedMaxP2pPeers(kEnvValue);
}

// ---------------------------------------------------------------------------
// Neither set: the field stays UNDEF and the divisor resolves to nRanks. This is
// what makes the feature a no-op by default.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, Default_LeavesUndefAndP2pMaxPeersEqualsNRanks)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    unsetenv("NCCL_P2P_MAX_PEERS");
    configured_value_ = kLeaveConfigUnset;

    if(!maxP2pPeersEnvCachedAs(NCCL_CONFIG_UNDEF_INT))
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());

    expectResolvedMaxP2pPeers(NCCL_CONFIG_UNDEF_INT, MPIEnvironment::world_size);
}

// ---------------------------------------------------------------------------
// A request above the rank count is capped, not rejected (init.cc initTransportsRank).
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, AboveRankCount_CappedToNRanks)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    unsetenv("NCCL_P2P_MAX_PEERS");
    if(!maxP2pPeersEnvCachedAs(NCCL_CONFIG_UNDEF_INT))
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";

    const int world_size = MPIEnvironment::world_size;
    configured_value_    = world_size * 4;

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());

    expectResolvedMaxP2pPeers(world_size);
}

// ---------------------------------------------------------------------------
// A config value <= 0 is rejected at init. Note the asymmetry: the env ignores it.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, Zero_RejectedWithInvalidArgument)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    configured_value_ = 0;

    ASSERT_MPI_EQ(ncclInvalidArgument, tryCreateCommunicator());
    ASSERT_MPI_TRUE(test_comm_ == nullptr);
}

// ---------------------------------------------------------------------------
// The halving loop only runs when nNodes > 1, so this is where the knob changes the
// mapping on real hardware. Seeds and pool sizes are arch/NIC dependent, so this
// derives its expectation from the observed pool rather than a constant.
//
// Scope: this checks plumbing and invariants, not the divisor. The halving loop reads
// divUp(maxP2pPeers, NCCL_MAX_DEV_WORK_P2P_PER_BATCH), which is 1 for every value below
// 3, so small requests cannot be told apart here. MultiNode_SaturateDividesByMaxP2pPeers
// below is the case that pins an exact value.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, MultiNode_PerPeerChannelsRespondToMaxP2pPeers)
{
    if(!validateTestPrerequisites(kMinProcessesForMPI,
                                  kNoProcessLimit,
                                  kNoPowerOfTwoRequired,
                                  /*min_nodes=*/2))
    {
        GTEST_SKIP() << "Requires >= 2 nodes so the per-peer halving loop runs";
    }

    unsetenv("NCCL_P2P_MAX_PEERS");
    if(!maxP2pPeersEnvCachedAs(NCCL_CONFIG_UNDEF_INT))
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";

    configured_value_ = kLeaveConfigUnset;
    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());
    const int perpeer_default = getActiveCommunicator()->p2pnChannelsPerPeer;
    const int pool_default    = getActiveCommunicator()->p2pnChannels;
    cleanupTestCommunicator();

    configured_value_ = 2;
    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());
    const int perpeer_limited = getActiveCommunicator()->p2pnChannelsPerPeer;
    const int pool_limited    = getActiveCommunicator()->p2pnChannels;

    TEST_INFO("p2pnChannelsPerPeer: default=%d (pool %d), maxP2pPeers=2 -> %d (pool %d)",
              perpeer_default, pool_default, perpeer_limited, pool_limited);

    // The requested value reached this comm intact.
    ASSERT_MPI_EQ(getActiveCommunicator()->p2pMaxPeers, 2);
    // The peer count must not move the channel pool itself.
    ASSERT_MPI_EQ(pool_limited, pool_default);
    // Fewer declared peers can only stop the reduction earlier, never later.
    ASSERT_MPI_TRUE(perpeer_limited >= perpeer_default);
    // ncclP2pChannelToPart cannot recover parts >= the pool.
    ASSERT_MPI_TRUE(perpeer_limited <= pool_limited);

    expectAllRanksAgree(perpeer_limited);
}

// ---------------------------------------------------------------------------
// The exact-value case. With RCCL_SATURATE_P2P_NCHANNELS on, the per-peer count is
// pow2Down(p2pnChannels / maxP2pPeers) outright, with no dependence on the topology
// seed, so the expected result follows from the observed pool alone. Dividing by
// nRanks instead lands on pool/nRanks, which differs whenever nRanks > 2, so this
// case fails if the divisor regresses.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, MultiNode_SaturateDividesByMaxP2pPeers)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    // Needs a rank count the nRanks divisor would distinguish from 2.
    if(MPIEnvironment::world_size <= 2)
        GTEST_SKIP() << "Needs > 2 ranks for the nRanks divisor to differ from 2";

    unsetenv("NCCL_P2P_MAX_PEERS");
    if(!maxP2pPeersEnvCachedAs(NCCL_CONFIG_UNDEF_INT))
        GTEST_SKIP() << "NCCL_P2P_MAX_PEERS already cached this process; "
                        "run this test in its own mpirun invocation.";
    setenv("RCCL_SATURATE_P2P_NCHANNELS", "1", /*overwrite=*/1);
    if(rcclParamSaturateP2pNChannels() != 1)
        GTEST_SKIP() << "RCCL_SATURATE_P2P_NCHANNELS already cached this process; "
                        "run this test in its own mpirun invocation.";

    configured_value_ = 2;
    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());
    const int perpeer = getActiveCommunicator()->p2pnChannelsPerPeer;
    int       pool    = getActiveCommunicator()->p2pnChannels;

    TEST_INFO("saturate on, maxP2pPeers=2: pool=%d p2pnChannelsPerPeer=%d", pool, perpeer);

    // Reduce before deciding: a per-rank skip here would leave the others in the
    // ASSERT_MPI_* allreduces below.
    int min_pool = 0;
    ASSERT_MPI_SUCCESS(MPI_Allreduce(&pool, &min_pool, 1, MPI_INT, MPI_MIN, MPI_COMM_WORLD));
    if(min_pool < 4) GTEST_SKIP() << "Pool too small for the halves to differ";

    ASSERT_MPI_EQ(getActiveCommunicator()->p2pMaxPeers, 2);
    // pow2Down(pool / 2) == pool / 2, the pool being a power of two by this point.
    ASSERT_MPI_EQ(perpeer, pool / 2);
    expectAllRanksAgree(perpeer);
}

// ---------------------------------------------------------------------------
// Data correctness under a limited peer count: a broken channel mapping shows up as
// wrong data or a hang, not an error code.
// ---------------------------------------------------------------------------
TEST_F(MaxP2pPeersMPITest, Functional_AlltoAll_WithMaxP2pPeers)
{
    ASSERT_MPI_TRUE(validateTestPrerequisites(kMinProcessesForMPI));

    configured_value_ = 2;

    ASSERT_MPI_EQ(ncclSuccess, createTestCommunicator());
    expectFunctionalAllToAll();
}

#endif // MPI_TESTS_ENABLED
